-- ════════════════════════════════════════════════════════════════════════
--  SGA — Controle de Pragas / Dedetização (FR 861 Rev.00)
--
--  Fluxo: usuário SOLICITA → operador ANALISA (isolamento, escopo,
--  parecer) → AGENDA → registra REALIZADO/NÃO REALIZADO.
--  Indicadores: aparições por área, tipo de praga e reincidências.
--
--  Como aplicar: Supabase → SQL Editor → New query → cole tudo → Run.
--  Seguro de rodar mais de uma vez.
-- ════════════════════════════════════════════════════════════════════════

create table if not exists public.dedetizacao_solicitacoes (
    id                      bigint generated by default as identity primary key,
    created_at              timestamptz default now(),

    -- Identificação
    solicitante             text,
    area_solicitante        text,
    empresa                 text,

    -- Solicitação
    motivo                  text,
    tipo_praga              text,           -- Rasteiros, Voadores, Roedores, Cupins, Escorpiões, Outros
    endereco                text,
    localizacao             text,           -- localização exata do serviço
    descricao               text,
    prioridade              text default 'Média',
    situacao                text default 'Pendente',   -- Pendente | Em análise | Agendado | Realizado | Não realizado
    data_agendamento        date,
    justificativa           text,

    -- Análise da solicitação (operador)
    necessidade_isolamento  boolean,
    tempo_isolamento        text,
    escopo_contrato         boolean,
    tamanho_area            text,
    parecer_empresa         text,
    ciencia_gestao          text,
    analisado_por           text,
    analisado_em            timestamptz,
    realizado_em            timestamptz
);

create index if not exists idx_dedet_area     on public.dedetizacao_solicitacoes (area_solicitante);
create index if not exists idx_dedet_situacao on public.dedetizacao_solicitacoes (situacao);
